/**
 * Playwright Configuration Generator
 * Generates optimized playwright.config.ts for target projects
 */

export interface PlaywrightConfigOptions {
  baseURL: string;
  testDir?: string;           // default: './e2e'
  parallel?: boolean;         // default: true
  workers?: number | 'auto';  // default: 'auto'
  retries?: number;           // default: 2 in CI, 0 locally
  timeout?: number;           // default: 30000
  screenshot?: 'off' | 'on' | 'only-on-failure';
  trace?: 'off' | 'on' | 'retain-on-failure';
}

/**
 * Generate an optimized Playwright configuration file content
 */
export function generatePlaywrightConfig(options: PlaywrightConfigOptions): string {
  const {
    baseURL,
    testDir = './e2e',
    parallel = true,
    workers = 'auto',
    retries,
    timeout = 30000,
    screenshot = 'only-on-failure',
    trace = 'retain-on-failure',
  } = options;

  // Determine workers line - omit entirely for auto (Playwright auto-detects)
  const workersLine = workers === 'auto' 
    ? '/* workers: undefined - auto-detected */'
    : `workers: process.env.CI ? 2 : ${workers},`;

  // Determine retries config
  const retriesConfig = retries !== undefined 
    ? retries 
    : 'process.env.CI ? 2 : 0';

  const config = `import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright configuration generated by Raiken
 * @see https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  testDir: '${testDir}',
  
  /* Run tests in files in parallel */
  fullyParallel: ${parallel},
  
  /* Fail the build on CI if you accidentally left test.only in the source code */
  forbidOnly: !!process.env.CI,
  
  /* Retry on CI only */
  retries: ${retriesConfig},
  
  /* Workers configuration */
  ${workersLine}
  
  /* Reporter to use */
  reporter: [
    ['html', { open: 'never' }],
    ['json', { outputFile: 'test-results/results.json' }],
    ['list'],
  ],
  
  /* Shared settings for all the projects below */
  use: {
    /* Base URL to use in actions like await page.goto('/') */
    baseURL: '${baseURL}',

    /* Collect trace when retrying the failed test */
    trace: '${trace}',
    
    /* Capture screenshot on failure */
    screenshot: '${screenshot}',
    
    /* Maximum time each action can take */
    actionTimeout: 10000,
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run dev',
  //   url: '${baseURL}',
  //   reuseExistingServer: !process.env.CI,
  // },

  /* Global test timeout */
  timeout: ${timeout},
  
  /* Expect timeout */
  expect: {
    timeout: 5000,
  },
});
`;

  return config;
}

/**
 * Check if a playwright config already exists
 */
export async function playwrightConfigExists(projectPath: string, configPath?: string): Promise<boolean> {
  const fs = await import('node:fs/promises');
  const path = await import('node:path');

  if (configPath) {
    const resolvedPath = path.isAbsolute(configPath)
      ? configPath
      : path.join(projectPath, configPath);
    try {
      await fs.access(resolvedPath);
      return true;
    } catch {
      return false;
    }
  }
  
  const possibleNames = [
    'playwright.config.ts',
    'playwright.config.js',
    'playwright.config.mjs',
  ];
  
  for (const name of possibleNames) {
    try {
      await fs.access(path.join(projectPath, name));
      return true;
    } catch {
      // File doesn't exist, continue checking
    }
  }
  
  return false;
}

/**
 * Write playwright config to a project
 */
export async function writePlaywrightConfig(
  projectPath: string, 
  options: PlaywrightConfigOptions,
  configPath?: string
): Promise<{ success: boolean; path: string; message: string }> {
  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  
  const configContent = generatePlaywrightConfig(options);
  const resolvedPath = configPath
    ? (path.isAbsolute(configPath) ? configPath : path.join(projectPath, configPath))
    : path.join(projectPath, 'playwright.config.ts');
  
  try {
    await fs.writeFile(resolvedPath, configContent, 'utf-8');
    return {
      success: true,
      path: resolvedPath,
      message: 'Created playwright.config.ts with optimized settings',
    };
  } catch (error) {
    return {
      success: false,
      path: resolvedPath,
      message: `Failed to write config: ${error instanceof Error ? error.message : 'Unknown error'}`,
    };
  }
}
