/**
 * Playwright Configuration Generator
 * Generates optimized playwright.config.ts for target projects
 */

export interface PlaywrightConfigOptions {
    testDir?: string; // default: './e2e'
    parallel?: boolean; // default: true
    workers?: number | "auto"; // default: 'auto'
    retries?: number; // default: 2 in CI, 0 locally
    timeout?: number; // default: 30000
    screenshot?: "off" | "on" | "only-on-failure";
    trace?: "off" | "on" | "retain-on-failure";
}

/**
 * Generate an optimized Playwright configuration file content.
 * No baseURL is set — tests should always use full URLs so they
 * work regardless of which application or port is being tested.
 */
export function generatePlaywrightConfig(options: PlaywrightConfigOptions): string {
    const {
        testDir = "./e2e",
        parallel = true,
        workers = "auto",
        retries,
        timeout = 30000,
        screenshot = "only-on-failure",
        trace = "retain-on-failure",
    } = options;

    const workersLine =
        workers === "auto"
            ? "/* workers: undefined - auto-detected */"
            : `workers: process.env.CI ? 2 : ${workers},`;

    const retriesConfig = retries !== undefined ? retries : "process.env.CI ? 2 : 0";

    const config = `import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright configuration generated by Raiken
 * @see https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  testDir: '${testDir}',
  
  /* Run tests in files in parallel */
  fullyParallel: ${parallel},
  
  /* Fail the build on CI if you accidentally left test.only in the source code */
  forbidOnly: !!process.env.CI,
  
  /* Retry on CI only */
  retries: ${retriesConfig},
  
  /* Workers configuration */
  ${workersLine}
  
  /* Reporter to use */
  reporter: [
    ['html', { open: 'never' }],
    ['json', { outputFile: 'test-results/results.json' }],
    ['list'],
  ],
  
  /* Shared settings for all the projects below */
  use: {
    /* Collect trace when retrying the failed test */
    trace: '${trace}',
    
    /* Capture screenshot on failure */
    screenshot: '${screenshot}',
    
    /* Maximum time each action can take */
    actionTimeout: 10000,
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  /* Global test timeout */
  timeout: ${timeout},
  
  /* Expect timeout */
  expect: {
    timeout: 5000,
  },
});
`;

    return config;
}

/** Config filenames Playwright itself will auto-discover, in resolution order. */
const PLAYWRIGHT_CONFIG_CANDIDATES = [
    "playwright.config.ts",
    "playwright.config.js",
    "playwright.config.mts",
    "playwright.config.mjs",
    "playwright.config.cjs",
];

/**
 * Find the first existing Playwright config file in a project, so callers
 * can pass an explicit `--config <path>` to the CLI instead of relying on
 * Playwright's own cwd-based auto-discovery — which silently no-ops (falls
 * back to defaults) for monorepos where the config lives in a package
 * subdirectory rather than at `projectPath`.
 *
 * Shared by every code path that shells out to `npx playwright test`
 * (dashboard `runTests`, the agent's `TestRunner`) so they resolve the same
 * config the same way instead of drifting.
 */
export async function findPlaywrightConfigPath(projectPath: string): Promise<string | null> {
    const fs = await import("node:fs/promises");
    const path = await import("node:path");

    for (const name of PLAYWRIGHT_CONFIG_CANDIDATES) {
        const fullPath = path.join(projectPath, name);
        try {
            await fs.access(fullPath);
            return fullPath;
        } catch {
            // continue
        }
    }

    return null;
}

/**
 * Check if a playwright config already exists
 */
export async function playwrightConfigExists(
    projectPath: string,
    configPath?: string,
): Promise<boolean> {
    const fs = await import("node:fs/promises");
    const path = await import("node:path");

    if (configPath) {
        const resolvedPath = path.isAbsolute(configPath)
            ? configPath
            : path.join(projectPath, configPath);
        try {
            await fs.access(resolvedPath);
            return true;
        } catch {
            return false;
        }
    }

    const possibleNames = ["playwright.config.ts", "playwright.config.js", "playwright.config.mjs"];

    for (const name of possibleNames) {
        try {
            await fs.access(path.join(projectPath, name));
            return true;
        } catch {
            // File doesn't exist, continue checking
        }
    }

    return false;
}

/**
 * Best-effort extraction of `use.baseURL` from an existing
 * `playwright.config.{ts,js,mjs,cjs}`.
 *
 * We never *execute* the config (it can import workspace packages or Node
 * builtins that may not be installed in the agent process). Instead we scan
 * the source for the first plausible `baseURL` assignment inside a `use:`
 * block and return its string literal. Returns `null` when:
 *   - no playwright config file exists
 *   - the file exists but has no `baseURL` field, or
 *   - the value isn't a static string literal we can reliably extract
 *
 * This is intentionally conservative: a `baseURL: process.env.FOO` value
 * returns `null` so the caller can fall back to other URL sources rather than
 * silently passing through unevaluated source text.
 */
export async function readPlaywrightBaseURL(projectPath: string): Promise<string | null> {
    const fs = await import("node:fs/promises");
    const path = await import("node:path");

    const candidates = [
        "playwright.config.ts",
        "playwright.config.mts",
        "playwright.config.js",
        "playwright.config.mjs",
        "playwright.config.cjs",
    ];

    for (const candidate of candidates) {
        let content: string;
        try {
            content = await fs.readFile(path.join(projectPath, candidate), "utf-8");
        } catch {
            continue;
        }

        // Find the first `baseURL` assignment with a static string literal.
        // Tolerates spaces, quote styles, and trailing commas. Multiline-safe.
        const match = content.match(/baseURL\s*:\s*(["'`])([^"'`\n\r]+)\1/);
        if (match?.[2]) {
            const value = match[2].trim();
            if (value.length > 0) return value;
        }
    }

    return null;
}

/**
 * Best-effort extraction of `testDir` from an existing Playwright config,
 * mirroring {@link readPlaywrightBaseURL}'s conservative static-string-only
 * approach (never executes the config). Used to detect drift against
 * `raiken.config.json`'s `testDirectory`, which is edited independently and
 * can silently fall out of sync with the config Playwright actually runs.
 */
export async function readPlaywrightTestDir(projectPath: string): Promise<string | null> {
    const fs = await import("node:fs/promises");
    const path = await import("node:path");

    const candidates = [
        "playwright.config.ts",
        "playwright.config.mts",
        "playwright.config.js",
        "playwright.config.mjs",
        "playwright.config.cjs",
    ];

    for (const candidate of candidates) {
        let content: string;
        try {
            content = await fs.readFile(path.join(projectPath, candidate), "utf-8");
        } catch {
            continue;
        }

        const match = content.match(/testDir\s*:\s*(["'`])\.?\/?([^"'`\n\r]+)\1/);
        if (match?.[2]) {
            const value = match[2].trim().replace(/\/+$/, "");
            if (value.length > 0) return value;
        }
    }

    return null;
}

/**
 * Write playwright config to a project
 */
export async function writePlaywrightConfig(
    projectPath: string,
    options: PlaywrightConfigOptions,
    configPath?: string,
): Promise<{ success: boolean; path: string; message: string }> {
    const fs = await import("node:fs/promises");
    const path = await import("node:path");

    const configContent = generatePlaywrightConfig(options);
    const resolvedPath = configPath
        ? path.isAbsolute(configPath)
            ? configPath
            : path.join(projectPath, configPath)
        : path.join(projectPath, "playwright.config.ts");

    try {
        await fs.writeFile(resolvedPath, configContent, "utf-8");
        return {
            success: true,
            path: resolvedPath,
            message: "Created playwright.config.ts with optimized settings",
        };
    } catch (error) {
        return {
            success: false,
            path: resolvedPath,
            message: `Failed to write config: ${error instanceof Error ? error.message : "Unknown error"}`,
        };
    }
}
