import type { ActivityEntry, Comment, Project, Task, User } from "../types";

export const SEED_USERS: User[] = [
    {
        id: "u_admin",
        username: "admin",
        email: "admin@raiken.dev",
        role: "admin",
        avatarColor: "#ef4444",
    },
    {
        id: "u_amelia",
        username: "amelia",
        email: "amelia@raiken.dev",
        role: "member",
        avatarColor: "#3b82f6",
    },
    {
        id: "u_jordan",
        username: "jordan",
        email: "jordan@raiken.dev",
        role: "member",
        avatarColor: "#22c55e",
    },
    {
        id: "u_priya",
        username: "priya",
        email: "priya@raiken.dev",
        role: "member",
        avatarColor: "#f59e0b",
    },
];

export const SEED_PROJECTS: Project[] = [
    {
        id: "p_orion",
        name: "Orion Launch",
        slug: "orion-launch",
        description: "Public launch of the Orion analytics dashboard.",
        status: "active",
        ownerId: "u_admin",
        memberIds: ["u_admin", "u_amelia", "u_jordan"],
        createdAt: "2026-01-12T09:00:00.000Z",
        updatedAt: "2026-04-19T10:00:00.000Z",
    },
    {
        id: "p_atlas",
        name: "Atlas Migration",
        slug: "atlas-migration",
        description: "Migrate the legacy Atlas service to the new infra.",
        status: "active",
        ownerId: "u_amelia",
        memberIds: ["u_amelia", "u_priya"],
        createdAt: "2026-02-01T13:30:00.000Z",
        updatedAt: "2026-04-20T15:45:00.000Z",
    },
    {
        id: "p_nimbus",
        name: "Nimbus Platform",
        slug: "nimbus-platform",
        description: "Internal platform for spinning up review environments.",
        status: "on_hold",
        ownerId: "u_jordan",
        memberIds: ["u_jordan", "u_priya"],
        createdAt: "2025-11-04T08:15:00.000Z",
        updatedAt: "2026-03-02T11:20:00.000Z",
    },
    {
        id: "p_helix",
        name: "Helix Redesign",
        slug: "helix-redesign",
        description: "Visual refresh and accessibility pass for the Helix app.",
        status: "active",
        ownerId: "u_priya",
        memberIds: ["u_priya", "u_amelia", "u_jordan"],
        createdAt: "2026-03-18T07:50:00.000Z",
        updatedAt: "2026-04-21T18:10:00.000Z",
    },
    {
        id: "p_legacy",
        name: "Legacy Reporting",
        slug: "legacy-reporting",
        description: "Maintenance work for the deprecated reporting suite.",
        status: "archived",
        ownerId: "u_admin",
        memberIds: ["u_admin"],
        createdAt: "2025-08-22T14:25:00.000Z",
        updatedAt: "2026-01-30T09:00:00.000Z",
    },
];

export const SEED_TASKS: Task[] = [
    {
        id: "t_orion_1",
        projectId: "p_orion",
        title: "Wire production analytics events",
        description: "Send pageview, signup and conversion events to Snowplow.",
        status: "in_progress",
        priority: "high",
        assigneeId: "u_amelia",
        dueDate: "2026-04-30T00:00:00.000Z",
        createdAt: "2026-04-01T10:00:00.000Z",
        updatedAt: "2026-04-19T10:00:00.000Z",
    },
    {
        id: "t_orion_2",
        projectId: "p_orion",
        title: "Draft launch announcement",
        description: "Blog post and changelog entry, signed off by marketing.",
        status: "todo",
        priority: "medium",
        assigneeId: "u_jordan",
        dueDate: "2026-05-04T00:00:00.000Z",
        createdAt: "2026-04-05T11:00:00.000Z",
        updatedAt: "2026-04-05T11:00:00.000Z",
    },
    {
        id: "t_orion_3",
        projectId: "p_orion",
        title: "Add 99th-percentile latency budget",
        description: "Page load p99 under 1.2s on the dashboard route.",
        status: "review",
        priority: "urgent",
        assigneeId: "u_admin",
        dueDate: "2026-04-28T00:00:00.000Z",
        createdAt: "2026-04-12T09:30:00.000Z",
        updatedAt: "2026-04-21T08:00:00.000Z",
    },
    {
        id: "t_orion_4",
        projectId: "p_orion",
        title: "QA: cross-browser sweep",
        description: "Verify the dashboard on Chrome, Firefox and Safari.",
        status: "done",
        priority: "medium",
        assigneeId: "u_amelia",
        dueDate: null,
        createdAt: "2026-04-08T14:00:00.000Z",
        updatedAt: "2026-04-18T16:30:00.000Z",
    },
    {
        id: "t_atlas_1",
        projectId: "p_atlas",
        title: "Cut-over plan for the user service",
        description: "Document the rollback path and on-call runbook.",
        status: "in_progress",
        priority: "high",
        assigneeId: "u_priya",
        dueDate: "2026-05-02T00:00:00.000Z",
        createdAt: "2026-03-22T13:00:00.000Z",
        updatedAt: "2026-04-20T15:45:00.000Z",
    },
    {
        id: "t_atlas_2",
        projectId: "p_atlas",
        title: "Shadow traffic to new infra",
        description: "Mirror 10% of read traffic for 48h and compare.",
        status: "todo",
        priority: "medium",
        assigneeId: null,
        dueDate: null,
        createdAt: "2026-04-04T09:00:00.000Z",
        updatedAt: "2026-04-04T09:00:00.000Z",
    },
    {
        id: "t_helix_1",
        projectId: "p_helix",
        title: "Audit color contrast on critical screens",
        description: "Hit WCAG AA across login, dashboard and settings.",
        status: "in_progress",
        priority: "high",
        assigneeId: "u_priya",
        dueDate: "2026-05-01T00:00:00.000Z",
        createdAt: "2026-04-02T10:00:00.000Z",
        updatedAt: "2026-04-21T18:10:00.000Z",
    },
    {
        id: "t_helix_2",
        projectId: "p_helix",
        title: "Replace ad-hoc icon set",
        description: "Standardise on a single 24px icon system.",
        status: "todo",
        priority: "low",
        assigneeId: "u_amelia",
        dueDate: null,
        createdAt: "2026-04-10T11:30:00.000Z",
        updatedAt: "2026-04-10T11:30:00.000Z",
    },
    {
        id: "t_nimbus_1",
        projectId: "p_nimbus",
        title: "PR-environment provisioning script",
        description: "Spin up an isolated stack per PR, tear down on close.",
        status: "review",
        priority: "high",
        assigneeId: "u_jordan",
        dueDate: null,
        createdAt: "2026-02-12T08:00:00.000Z",
        updatedAt: "2026-03-02T11:20:00.000Z",
    },
];

export const SEED_COMMENTS: Comment[] = [
    {
        id: "c_orion_1",
        taskId: "t_orion_1",
        authorId: "u_admin",
        body: "Make sure conversion events fire on the server side too.",
        createdAt: "2026-04-15T10:00:00.000Z",
    },
    {
        id: "c_orion_2",
        taskId: "t_orion_1",
        authorId: "u_amelia",
        body: "Done — added a unit test for the server-side pipeline.",
        createdAt: "2026-04-19T09:55:00.000Z",
    },
    {
        id: "c_atlas_1",
        taskId: "t_atlas_1",
        authorId: "u_priya",
        body: "Runbook draft ready for review.",
        createdAt: "2026-04-20T15:40:00.000Z",
    },
];

export const SEED_ACTIVITY: ActivityEntry[] = [
    {
        id: "a_1",
        projectId: "p_orion",
        actorId: "u_admin",
        kind: "task_status_changed",
        summary: 'moved "Add 99th-percentile latency budget" to Review',
        timestamp: "2026-04-21T08:00:00.000Z",
    },
    {
        id: "a_2",
        projectId: "p_helix",
        actorId: "u_priya",
        kind: "task_created",
        summary: 'added task "Audit color contrast on critical screens"',
        timestamp: "2026-04-02T10:00:00.000Z",
    },
    {
        id: "a_3",
        projectId: "p_atlas",
        actorId: "u_amelia",
        kind: "comment_added",
        summary: 'commented on "Cut-over plan for the user service"',
        timestamp: "2026-04-20T15:45:00.000Z",
    },
    {
        id: "a_4",
        projectId: "p_orion",
        actorId: "u_amelia",
        kind: "comment_added",
        summary: 'commented on "Wire production analytics events"',
        timestamp: "2026-04-19T09:55:00.000Z",
    },
    {
        id: "a_5",
        projectId: "p_orion",
        actorId: "u_amelia",
        kind: "task_status_changed",
        summary: 'moved "QA: cross-browser sweep" to Done',
        timestamp: "2026-04-18T16:30:00.000Z",
    },
];
