/**
 * Build a portable Markdown snapshot of the project's testing state.
 *
 * The output is consumed by IDE-side AI agents (Cursor, Claude, Copilot) so
 * they can answer "what's tested? what changed? what's flaky?" without us
 * needing to ship an MCP server. The file is intentionally small and
 * stable — agents tend to truncate large context aggressively.
 *
 * Inputs are read-only: we never write to the database here.
 */

import { execSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { GraphQueryService } from "../analysis/graph-query";
import { defaultBaseRef, getChangedFiles, getStagedFiles, resolveRefs } from "../ci/git-diff";
import { CodeGraphDB } from "../database/db";

export interface ContextOptions {
    projectPath: string;
    /** Output file path. Default: <projectPath>/raiken.ctx.md. */
    outputPath?: string;
    /** Cap on lines printed in each section. */
    maxRowsPerSection?: number;
    /** Whether to include the current-branch impact section. Default: true. */
    includeImpact?: boolean;
}

export interface ContextResult {
    outputPath: string;
    bytesWritten: number;
    sections: {
        graph: boolean;
        impact: boolean;
        failures: boolean;
        coverage: boolean;
    };
}

const DEFAULT_MAX_ROWS = 25;

export async function writeProjectContext(options: ContextOptions): Promise<ContextResult> {
    const projectPath = path.resolve(options.projectPath);
    const outputPath = path.resolve(projectPath, options.outputPath ?? "raiken.ctx.md");
    const maxRows = options.maxRowsPerSection ?? DEFAULT_MAX_ROWS;

    const sections = {
        graph: false,
        impact: false,
        failures: false,
        coverage: false,
    };

    const lines: string[] = [];
    lines.push("# Raiken project context");
    lines.push("");
    lines.push(
        "_Auto-generated by `raiken context`. Pass to your IDE agent for grounded answers " +
            "about what is tested, what changed, and what is flaky in this project._",
    );
    lines.push("");
    lines.push(`Generated: ${new Date().toISOString()}`);
    lines.push(`Project:   ${projectName(projectPath)}`);
    lines.push(`Branch:    ${currentBranch(projectPath) ?? "(unknown)"}`);
    lines.push("");

    sections.graph = appendGraphSection(lines, projectPath);
    if (options.includeImpact !== false) {
        sections.impact = appendImpactSection(lines, projectPath, maxRows);
    }
    sections.failures = appendFailuresSection(lines, projectPath, maxRows);
    sections.coverage = appendCoverageSection(lines, projectPath, maxRows);

    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push(
        "When using this context: prefer concrete file paths over guesses. If you propose " +
            "a new test, place it under the project's test directory and avoid hardcoded " +
            "sleeps (`page.waitForTimeout`, `setTimeout`).",
    );
    lines.push("");

    const body = lines.join("\n");
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, body, "utf-8");

    return { outputPath, bytesWritten: Buffer.byteLength(body, "utf-8"), sections };
}

// ---------------------------------------------------------------------------
// Sections
// ---------------------------------------------------------------------------

function appendGraphSection(lines: string[], projectPath: string): boolean {
    const query = new GraphQueryService(projectPath);
    let summary: ReturnType<typeof query.summary>;
    try {
        summary = query.summary();
    } catch {
        return false;
    }

    lines.push("## Code graph");
    lines.push("");
    lines.push(`- Symbols: ${summary.symbols}`);
    lines.push(`- Edges:   ${summary.edges}`);
    if (summary.edges > 0) {
        const top = Object.entries(summary.edgesByKind)
            .sort((a, b) => b[1] - a[1])
            .slice(0, 6);
        lines.push("- Edge kinds:");
        for (const [kind, count] of top) {
            lines.push(`  - ${kind}: ${count}`);
        }
    }
    lines.push("");
    return true;
}

function appendImpactSection(lines: string[], projectPath: string, maxRows: number): boolean {
    let changed: ReturnType<typeof getChangedFiles>;
    let scope: string;
    try {
        // Prefer the staged snapshot if anything is staged (mirrors what
        // a pre-commit hook would see); otherwise diff against the default
        // base. This keeps the file useful both mid-edit and post-commit.
        const staged = getStagedFiles(projectPath);
        if (staged.length > 0) {
            changed = staged;
            scope = "staged (HEAD → index)";
        } else {
            const base = defaultBaseRef(projectPath);
            const refs = resolveRefs(projectPath, base, "HEAD");
            changed = getChangedFiles(projectPath, refs);
            scope = `${refs.base}…${refs.head}`;
        }
    } catch {
        return false;
    }

    lines.push("## Pending changes");
    lines.push("");
    lines.push(`Scope: \`${scope}\` — ${changed.length} file(s).`);
    lines.push("");

    if (changed.length === 0) {
        lines.push("_No pending changes._");
        lines.push("");
        return true;
    }

    const sourceFiles = changed.filter((f) => f.status !== "removed").map((f) => f.path);
    const query = new GraphQueryService(projectPath);
    let evidence: ReturnType<typeof query.getAffectedTests>;
    try {
        evidence = query.getAffectedTests(sourceFiles);
    } catch {
        evidence = [];
    }

    const byTest = new Map<string, number>();
    for (const row of evidence) {
        byTest.set(row.testFile, Math.max(byTest.get(row.testFile) ?? 0, row.confidence));
    }
    const ranked = [...byTest.entries()].sort((a, b) => b[1] - a[1]).slice(0, maxRows);

    lines.push("### Affected tests");
    lines.push("");
    if (ranked.length === 0) {
        lines.push("_No tests found in graph for these files._");
    } else {
        lines.push("| Test file | Confidence |");
        lines.push("|---|---|");
        for (const [file, confidence] of ranked) {
            lines.push(`| \`${file}\` | ${confidence.toFixed(2)} |`);
        }
    }
    lines.push("");
    return true;
}

function appendFailuresSection(lines: string[], projectPath: string, maxRows: number): boolean {
    const db = new CodeGraphDB(projectPath);
    let failures: ReturnType<typeof db.getRecentFailures>;
    try {
        failures = db.getRecentFailures(maxRows);
    } catch {
        db.close();
        return false;
    }
    db.close();

    lines.push("## Recent failures");
    lines.push("");
    if (failures.length === 0) {
        lines.push("_No recent failures recorded._");
        lines.push("");
        return true;
    }

    lines.push("| Test | Error | When |");
    lines.push("|---|---|---|");
    for (const f of failures) {
        const when = f.lastRun ? new Date(f.lastRun).toISOString() : "(unknown)";
        const err = (f.errorMessage ?? "(no message)")
            .replace(/\|/g, "\\|")
            .replace(/\r?\n/g, " ")
            .slice(0, 120);
        const testName = (f.testName ?? "(anonymous)").replace(/\|/g, "\\|");
        lines.push(`| \`${f.testFile}\`::${testName} | ${err} | ${when} |`);
    }
    lines.push("");
    return true;
}

function appendCoverageSection(lines: string[], projectPath: string, maxRows: number): boolean {
    const db = new CodeGraphDB(projectPath);
    let files: ReturnType<typeof db.getFiles>;
    try {
        files = db.getFiles();
    } catch {
        db.close();
        return false;
    }
    db.close();

    if (files.length === 0) return false;

    // "Coverage" here is graph-level: source files that have at least one
    // test edge pointing at them. We compute it crudely by running the
    // graph-query for each source file batch — accurate enough for a
    // navigational hint without hammering the DB.
    const query = new GraphQueryService(projectPath);
    const sourceFiles = files.map((f) => f.relative_path).filter((p) => !isLikelyTest(p));

    let evidence: ReturnType<typeof query.getAffectedTests> = [];
    try {
        evidence = query.getAffectedTests(sourceFiles);
    } catch {
        // GraphQueryService swallows a lot internally; if it throws here
        // we just skip coverage rather than fail the whole context build.
    }
    const tested = new Set(evidence.map((e) => e.sourceFile));

    const untested = sourceFiles.filter((f) => !tested.has(f)).slice(0, maxRows);

    lines.push("## Coverage hints");
    lines.push("");
    lines.push(
        `- Source files: ${sourceFiles.length}` +
            `  · with at least one test edge: ${tested.size}` +
            `  · without: ${sourceFiles.length - tested.size}`,
    );
    lines.push("");

    if (untested.length > 0) {
        lines.push(`### Untested source files (top ${untested.length})`);
        lines.push("");
        for (const f of untested) lines.push(`- \`${f}\``);
        lines.push("");
    }

    return true;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function projectName(projectPath: string): string {
    try {
        const pkg = JSON.parse(
            fs.readFileSync(path.join(projectPath, "package.json"), "utf-8"),
        ) as { name?: string };
        return pkg.name ?? path.basename(projectPath);
    } catch {
        return path.basename(projectPath);
    }
}

function currentBranch(projectPath: string): string | null {
    try {
        return execSync("git rev-parse --abbrev-ref HEAD", {
            cwd: projectPath,
            encoding: "utf-8",
            stdio: ["pipe", "pipe", "pipe"],
        }).trim();
    } catch {
        return null;
    }
}

function isLikelyTest(filePath: string): boolean {
    const lower = filePath.toLowerCase();
    return (
        /\.(spec|test|e2e)\.[jt]sx?$/.test(lower) ||
        lower.includes("/tests/") ||
        lower.includes("/test/") ||
        lower.includes("/__tests__/") ||
        lower.includes("/e2e/")
    );
}
